cmd_drivers/net/wireless/mt5931/mgmt/rlm_protection.o := /root/android/kernel/techknow/toolchains/arm-eabi-linaro-4.6.2/bin/arm-eabi-gcc -Wp,-MD,drivers/net/wireless/mt5931/mgmt/.rlm_protection.o.d  -nostdinc -isystem /root/android/kernel/techknow/toolchains/arm-eabi-linaro-4.6.2/bin/../lib/gcc/arm-eabi/4.6.2/include -I/root/android/kernel/usumfabricae/Linux3188/arch/arm/include -Iarch/arm/include/generated -Iinclude  -include include/generated/autoconf.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-rk30/include -Iarch/arm/plat-rk/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Os -marm -fno-dwarf2-cfi-asm -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -DLINUX -DMT5931 -DCFG_SUPPORT_WAPI=0 -DCFG_SUPPORT_XLOG=0 -DCFG_SUPPORT_AEE=0 -D_HIF_SDIO=1 -DRSSI_ENHANCE=1 -DDBG=0 -Idrivers/net/wireless/mt5931/os -Idrivers/net/wireless/mt5931/os/linux/include -Idrivers/net/wireless/mt5931/os/linux/hif/sdio/include -Idrivers/net/wireless/mt5931/include -Idrivers/net/wireless/mt5931/include/nic -Idrivers/net/wireless/mt5931/include/mgmt  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(rlm_protection)"  -D"KBUILD_MODNAME=KBUILD_STR(wlan)" -c -o drivers/net/wireless/mt5931/mgmt/rlm_protection.o drivers/net/wireless/mt5931/mgmt/rlm_protection.c

source_drivers/net/wireless/mt5931/mgmt/rlm_protection.o := drivers/net/wireless/mt5931/mgmt/rlm_protection.c

deps_drivers/net/wireless/mt5931/mgmt/rlm_protection.o := \

drivers/net/wireless/mt5931/mgmt/rlm_protection.o: $(deps_drivers/net/wireless/mt5931/mgmt/rlm_protection.o)

$(deps_drivers/net/wireless/mt5931/mgmt/rlm_protection.o):
